apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      restartPolicy: Always
      containers:
        - name: app-container
          image: tomerkul/myflask:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST  
              value: db
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "develop"
            - name: DB_USER
              value: "tomer"
            - name: DB_PASSWORD
              value: "1234"

---
apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service-with-db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer

