version: '3'
services:
  web:
    build: ./application/
    ports:
      - 5000:5000
    depends_on:
      - db
    restart: always
  db:
    build: ./db/
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=develop
