version: '3'
services:
  web:
    image: tomerkul/myflask:latest
    ports:
      - 5000:5000
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: tomerkul/mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=develop
      - MYSQL_USER=tomer
      - MYSQL_PASSWORD=1234
    restart:  unless-stopped
